server:
  port: 8081
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://39.103.151.171:3306/youbo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 39.103.151.171
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: kobe
      cluster-nodes: 39.103.151.171:9300
      repositories:
        enabled: true
  rabbitmq:
    username: root
    password: admin   #password
    host: 39.103.151.171
    port: 5672
